name: veriff_flutter_plugin_platform_interface
description: A common platform interface for the veriff_flutter_plugin plugin.
version: 1.0.0
homepage:

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  veriff_flutter: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0