name: veriff_flutter_plugin
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  veriff_flutter_plugin_platform_interface:
    path: ../veriff_flutter_plugin_platform_interface
  veriff_flutter_plugin_web:
    path: ../veriff_flutter_plugin_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      web:
        default_package: veriff_flutter_plugin_web